---
- name: check status of services
  hosts: localhost
  tasks:
    - command:  service httpd status
      register: result

    - mail: 
       to: mostafa.hussien.fci@gmail.com
       subject: Service Alert
       body: Httpd Service is down

       when: result.stdout.find('down') != -1