---
- name: install and configure Mysql
  hosts: db-server
  tasks:
    - name: install pre requisites
      yum:
        name: pre-req-packages
        state:  present

    - name: install mysql  packages
      yum:
        name: mysql
        state:  started

    - name: configure database
      mysql_db:
        name: db1
        state:  present                