---
#install in localhost
-
  name: play1
  hosts: localhost
  tasks: 
    - name: execute command date
      command: date
    - name: install httpd service
      dnf:
        name: httpd
        state: present
    - name: start web server
      service:
        name: httpd
        state:  started
